improve circleci: separate scalafmt and scapegoat jobs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,6 +6,49 @@ version: 2.1
 orbs:
   codecov: codecov/codecov@1.0.2
 jobs:
+  check_scapegoat:
+    docker:
+      - image: circleci/openjdk:11-jdk
+    working_directory: ~/repo
+    environment:
+      TERM: dumb
+    steps:
+      - checkout
+
+      - restore_cache:
+          keys:
+            - v1-dependencies-{{ checksum "build.sbt" }}
+            - v1-dependencies-
+
+      - run:
+          name: Scapegoat check
+          command: |
+            sbt scapegoat
+            length=$(wc -l "target/scala-2.12/scapegoat-report/scapegoat.html" | awk '{print $1}')
+            if [[ $length -gt 66 ]]; then
+              echo "There are Scapegoat errors" && exit 1;
+            fi
+  check_scalafmt:
+    docker:
+      - image: circleci/openjdk:11-jdk
+    working_directory: ~/repo
+    environment:
+      TERM: dumb
+    steps:
+      - checkout
+
+      - restore_cache:
+          keys:
+            - v1-dependencies-{{ checksum "build.sbt" }}
+            - v1-dependencies-
+
+      - run:
+          name: Style check
+          command: |
+            sbt formatAll
+            if [[ -n $(git diff --name-only) ]]; then
+              echo "These files are not formatted correctly:" && git diff --name-only && exit 1;
+            fi
   build:
     docker:
       - image: circleci/openjdk:11-jdk
@@ -25,15 +68,6 @@ jobs:
             - v1-dependencies-{{ checksum "build.sbt" }}
             # fallback to using the latest cache if no exact match is found
             - v1-dependencies-
-
-      - run:
-          name: Style check
-          command: |
-            sbt formatAll
-            if [[ -n $(git diff --name-only) ]]; then
-              echo "These files are not formatted correctly:" && git diff --name-only && exit 1;
-            fi
-
       - run:
           name: Compile
           command: cat /dev/null | sbt compileAll
@@ -72,5 +106,7 @@ workflows:
   version: 2
   build_and_integration:
     jobs:
+      - check_scapegoat
+      - check_scalafmt
       - build
       - integration
